### ISSUE TITLE
Differences log.io <-> log.io-ng

### ISSUE THREAD

**Issue by rjwestman** [perint/log.io-ng#2]
I came here from a link in the issue tab of log.io on github. I couldn't find out what the differences are? In addition to that, it seems like the installation is exactly the same? (Sorry for the stupid questions)

**Comment by hanneshal** [comment]
You are absolutely right. We forked to project 3 days ago to put Log.io back on track. 
First thing on the list was to update the dependencies and allow users to install it, which is not possible at the moment for the "regular" Log.io. It refers to old dependencies and stuff we don't need. 

Next on the list ist update the code and add more documentation+updated test suite.
After that we will push it to npm, so users can just install it.

regards

Johannes
